[tools]
node = "24"

[tasks.dev-gui]
env = { NSB_WEBUI_PORT = "3100" }
run = { tasks = ["dev-desktop", "dev-webui"] }

[tasks.dev-desktop]
run = "watchexec -w ./gui/src -e rs -i target --shell=none -r -- cargo run -p nsb-gui"

[tasks.dev-webui]
run = "cd gui/webui && pnpm run dev"

[tasks.build-webui]
run = "cd gui/webui && pnpm run build"

[tasks.build-gui]
run = [
    {
      task = "build-webui",
    },
    "cargo build -p nsb-gui --release"
]
