// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileItem } from './ProfileItem';
import type { AppLanguage } from './AppLanguage';

export type AppConfig = {
  mixed_port: number;
  allow_lan: boolean;
  app_port: number;
  system_proxy_enabled: boolean;
  app_language: AppLanguage;
  profiles: Array<ProfileItem>;
  current_profile_id: string | null;
};
