// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLanguage } from './AppLanguage';
import type { ProfileItem } from './ProfileItem';
import type { ProfileTemplate } from './ProfileTemplate';

export type AppConfig = {
  app_port: number;
  system_proxy_enabled: boolean;
  app_language: AppLanguage;
  profiles: Array<ProfileItem>;
  templates: Array<ProfileTemplate>;
  current_profile_id: string | null;
};
