// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataImportEntityKind } from './DataImportEntityKind';
import type { DataImportIssueLevel } from './DataImportIssueLevel';

export type DataImportIssue = {
  level: DataImportIssueLevel;
  entity: DataImportEntityKind;
  id: string | null;
  name: string | null;
  reason: string;
};
