// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataImportEntityStats } from './DataImportEntityStats';
import type { DataImportIssue } from './DataImportIssue';

export type DataImportReport = {
  templates: DataImportEntityStats;
  profiles: DataImportEntityStats;
  issues: Array<DataImportIssue>;
};
