// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileRemote } from './ProfileRemote';

export type PortableProfile = {
  id: string;
  name: string;
  template_id: string;
  inline_template: string | null;
  remotes: Array<ProfileRemote>;
  hook: string | null;
  update_interval_hours: number | null;
  update_cron: string | null;
};
