// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortableProfile } from './PortableProfile';
import type { PortableTemplate } from './PortableTemplate';

export type PortableDataArchive = {
  format: string;
  version: number;
  templates: Array<PortableTemplate>;
  profiles: Array<PortableProfile>;
};
