// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileTemplate = {
  id: string;
  name: string;
  content: string;
  updated_at: number;
  reference_count: number;
};
