// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileSummary } from './ProfileSummary';

export type ProfileListResponse = {
  profiles: Array<ProfileSummary>;
  current_profile_id: string | null;
};
