// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { ProfileRemoteDnsKeepFields } from './ProfileRemoteDnsKeepFields';
import type { ProfileRemoteExperimentalKeepFields } from './ProfileRemoteExperimentalKeepFields';
import type { ProfileRemoteRouteKeepFields } from './ProfileRemoteRouteKeepFields';
import type { ProfileRemoteClashKeepFields } from './ProfileRemoteClashKeepFields';

export type ProfileRemoteKeepFields = {
  clash: ProfileRemoteClashKeepFields;
  outbounds: boolean;
  inbounds: boolean;
  dns: ProfileRemoteDnsKeepFields;
  route: ProfileRemoteRouteKeepFields;
  experimental: ProfileRemoteExperimentalKeepFields;
};
