// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileKind } from './ProfileKind';
import type { ProfileHeader } from './ProfileHeader';
import type { ProfileRemote } from './ProfileRemote';

export type ProfileItem = {
  id: string;
  name: string;
  kind: ProfileKind;
  url: string;
  updated_at: number;
  headers: Array<ProfileHeader>;
  remotes: Array<ProfileRemote>;
  hook: string | null;
  keep_subscription_groups_and_rules: boolean;
  update_interval_hours: number | null;
  update_cron: string | null;
  next_update_at: number;
  last_attempt_at: number;
  last_update_error: string | null;
  revision: number;
};
