// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileRemoteExperimentalClashApiKeepFields = {
  external_controller: boolean;
  external_ui: boolean;
  external_ui_download_url: boolean;
  external_ui_download_detour: boolean;
  secret: boolean;
  default_mode: boolean;
  access_control_allow_origin: boolean;
  access_control_allow_private_network: boolean;
  store_mode: boolean;
  store_selected: boolean;
  store_fakeip: boolean;
  cache_file: boolean;
  cache_id: boolean;
};
