// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileKind } from './ProfileKind';

export type ProfileSummary = {
  id: string;
  name: string;
  kind: ProfileKind;
  updated_at: number;
  last_attempt_at: number;
  last_update_failed: boolean;
};
