// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { ProfileRemoteDnsOptimisticKeepFields } from './ProfileRemoteDnsOptimisticKeepFields';

export type ProfileRemoteDnsKeepFields = {
  servers: boolean;
  rules: boolean;
  final: boolean;
  strategy: boolean;
  disable_cache: boolean;
  disable_expire: boolean;
  independent_cache: boolean;
  cache_capacity: boolean;
  optimistic: ProfileRemoteDnsOptimisticKeepFields;
  timeout: boolean;
  reverse_mapping: boolean;
  client_subnet: boolean;
  fakeip: boolean;
};
