// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileRemoteRouteKeepFields = {
  rules: boolean;
  rule_set: boolean;
  final: boolean;
  auto_detect_interface: boolean;
  override_android_vpn: boolean;
  default_interface: boolean;
  default_mark: boolean;
  find_process: boolean;
  find_neighbor: boolean;
  dhcp_lease_files: boolean;
  default_http_client: boolean;
  default_domain_resolver: boolean;
  default_network_strategy: boolean;
  default_network_type: boolean;
  default_fallback_network_type: boolean;
  default_fallback_delay: boolean;
};
