// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileRemoteExperimentalCacheFileKeepFields = {
  enabled: boolean;
  path: boolean;
  cache_id: boolean;
  store_fakeip: boolean;
  store_rdrc: boolean;
  rdrc_timeout: boolean;
  store_dns: boolean;
};
