// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileHeader } from './ProfileHeader';
import type { ProfileRemoteFormat } from './ProfileRemoteFormat';
import type { ProfileRemoteKeepFields } from './ProfileRemoteKeepFields';

export type ProfileRemote = {
  name: string;
  url: string;
  headers: Array<ProfileHeader>;
  format: ProfileRemoteFormat;
  keep: ProfileRemoteKeepFields;
};
