// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileRemoteKeepFields = {
  nodes: boolean;
  groups: boolean;
  route_final: boolean;
  route_rules: boolean;
};
