// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileRemote } from './ProfileRemote';

export type ProfileDetailResponse = {
  id: string;
  name: string;
  template_id: string;
  inline_template: Record<string, unknown> | null;
  updated_at: number;
  remotes: Array<ProfileRemote>;
  hook: string | null;
  update_interval_hours: number | null;
  update_cron: string | null;
  next_update_at: number;
  last_attempt_at: number;
  last_update_error: string | null;
  revision: number;
};
