// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { ProfileRemoteExperimentalCacheFileKeepFields } from './ProfileRemoteExperimentalCacheFileKeepFields';
import type { ProfileRemoteExperimentalClashApiKeepFields } from './ProfileRemoteExperimentalClashApiKeepFields';

export type ProfileRemoteExperimentalKeepFields = {
  cache_file: ProfileRemoteExperimentalCacheFileKeepFields;
  clash_api: ProfileRemoteExperimentalClashApiKeepFields;
  v2ray_api: boolean;
};
