// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileSummary = {
  id: string;
  name: string;
  updated_at: number;
  last_attempt_at: number;
  last_update_failed: boolean;
  last_update_error: string | null;
};
