// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileItem } from './ProfileItem';

export type ProfileListResponse = {
  profiles: Array<ProfileItem>;
  current_profile_id: string | null;
};
