import type { ProfileRemoteKeepFields } from '@/types';

export function createDefaultProfileRemoteKeepFields(): ProfileRemoteKeepFields {
  return {
    clash: {
      proxies: true,
    },
    outbounds: true,
    inbounds: false,
    dns: {
      servers: false,
      rules: false,
      final: false,
      strategy: false,
      disable_cache: false,
      disable_expire: false,
      independent_cache: false,
      cache_capacity: false,
      optimistic: { enabled: false, timeout: false },
      timeout: false,
      reverse_mapping: false,
      client_subnet: false,
      fakeip: false,
    },
    route: {
      rules: false,
      rule_set: false,
      final: false,
      auto_detect_interface: false,
      override_android_vpn: false,
      default_interface: false,
      default_mark: false,
      find_process: false,
      find_neighbor: false,
      dhcp_lease_files: false,
      default_http_client: false,
      default_domain_resolver: false,
      default_network_strategy: false,
      default_network_type: false,
      default_fallback_network_type: false,
      default_fallback_delay: false,
    },
    experimental: {
      cache_file: {
        enabled: false,
        path: false,
        cache_id: false,
        store_fakeip: false,
        store_rdrc: false,
        rdrc_timeout: false,
        store_dns: false,
      },
      clash_api: {
        external_controller: false,
        external_ui: false,
        external_ui_download_url: false,
        external_ui_download_detour: false,
        secret: false,
        default_mode: false,
        access_control_allow_origin: false,
        access_control_allow_private_network: false,
        store_mode: false,
        store_selected: false,
        store_fakeip: false,
        cache_file: false,
        cache_id: false,
      },
      v2ray_api: false,
    },
  };
}
